name: MacOS Ventura M1 install and test
'on':
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref
        default: master
        required: true
  schedule:
    - cron: "15 02 * * *"

jobs:

  install_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ventura]
        python-version: [3.9, "3.10"]
    steps:
    # This Checkout use git-ref keyword from dispatch
      - name: Clone Repository (Master)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}
      - name: Set up Python3 with brew
        run: |
          env
          echo $PATH
          export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
          which brew
          brew install python@${{ matrix.python-version }}
      - name: Run Installation of oq-engine in devel mode
        env:
          BRANCH: ${{ github.event.inputs.git-ref }}
        run: |
          set -x
          env
          echo $PATH
          export PATH=/opt/homebrew/bin:/opt/homebrew/sbin:$PATH
          echo "sqlite3 version"
          which sqlite3
          sqlite3 --version
          export PIP_DEFAULT_TIMEOUT=100
          python${{ matrix.python-version }} -V
          python${{ matrix.python-version }} -m pip install -U pip wheel
          #
          echo "branch to test: ${BRANCH}"
          if [[ "$BRANCH" != "" ]]
          then
            python${{ matrix.python-version }} install.py devel --version ${BRANCH}
          else
            python${{ matrix.python-version }} install.py devel
          fi
      - name: Run demos to test installation
        run: |
          source ~/openquake/bin/activate
          pip3 install pytest``
          oq --version
          oq dbserver start
          sleep 5
          # test for engine
          pytest -vsx --color=yes /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/openquake/sep
          #
          pytest -vsx --color=yes /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/openquake/hazardlib/tests/gsim/kotha_2020_test.py
          #
          pytest -vsx --color=yes /Users/runner/runner-isolation/actions-runner/_work/oq-engine/oq-engine/openquake/calculators
          # Run calc
          oq engine --run https://downloads.openquake.org/jobs/risk_test.zip
          # shutdown the VM to have new runner and wait
